apiVersion: v1
kind: Secret
metadata:
  name: lanthir-jwt-credentials
  labels:
    app: lanthir-services
type: Opaque
data:
  SigningKey: YzU2ZjY1Zjg0ZDEzY2QyYzA1N2VhZmI1NzVhOGFiYzFkMWE0OTQ1MTY2ZTU4MTVlMDVhMTEzNmRlZjUxODU1Mgo=
---
apiVersion: v1
kind: Service
metadata:
  name: lanthir-services-svc
  labels:
    app: lanthir-services
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: http
  selector:
    app: lanthir-services
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lanthir-services-config
  labels:
    app: lanthir-services-config
data:
  # Deployment specific configuration
  appsettings.json: |-
    {
      "Kestrel": {
        "EndPoints": {
          "Http": {
            "Url": "http://::8080"
          }
        }
      },
      "Jwt": {
        "Issuer": "lanthir-lunch",
        "ExpiryMinutes": 60,
        "RefreshExpiryHours": 24
      },
      "ConnectionStrings": {
        "LanthirDatabase": "Server=lanthir-mssql-db-svc;User Id=;Password=;Database=LanthirLunch"
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lanthir-services-deploy
  labels:
    app: lanthir-services
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lanthir-services
  minReadySeconds: 60
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: lanthir-services
    spec:
      containers:
        - name: lanthir-services
          imagePullPolicy: Always
          image: lanthir-services:latest
          env:
            - name: Jwt__SigningKey
              valueFrom:
                secretKeyRef:
                  name: lanthir-jwt-credentials
                  key: SigningKey
            - name: ConnectionStrings__LanthirDatabase_Credentials__Username
              valueFrom:
                secretKeyRef:
                  name: lanthir-mssql-db-credentials
                  key: MSSQL_USER
            - name: ConnectionStrings__LanthirDatabase_Credentials__Password
              valueFrom:
                secretKeyRef:
                  name: lanthir-mssql-db-credentials
                  key: MSSQL_PASSWORD
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5
          volumeMounts:
            - name: lanthir-services-config
              mountPath: /app/appsettings.local.json
              subPath: appsettings.json
      volumes:
        - name: lanthir-services-config
          configMap:
            name: lanthir-services-config
      imagePullSecrets:
        - name: academy-28ee1257-docker-registry
